### ISSUE TITLE
Additional .NET Regex Engine Support

### ISSUE THREAD

**Issue by DaniilVeriga** [bridgedotnet/Bridge#1167]
#701 introduced a lot of .NET Regex support, but some pieces are yet to be completed.

List of currently not supported features:

 - [ ] Character Classes:
   - [ ] Unicode categories `p{name}` and `\P{name}` #1823 
   - [ ] `\w` and `\W` do not work with Unicode #1825 
   - [x] Character class subtraction: `[base_group-[excluded_group]]` #1632
 - [x] Grouping Constructs:
   - [x] Balancing groups #1558 
   - [x] `imnsx` options #1375
   - [x] Lookbehind assertions #1551
   - [x] Nonbacktracking subexpression #1550
 - [x] Anchors: `\A` `\Z` `\z` `\G` #1364.
 - [x] Backreference Constructs: 
   - [x] `\k` #1376 
 - [x] Alternation Constructs #1557
 - [ ] Regular Expression Options:
   - [ ] `Compiled` #1826
   - [ ] `CultureInvariant` #1827
   - [ ] `ECMAScript` #1828 
   - [ ] `RightToLeft`#1829
   - [x] `ExplicitCapture` #1375
   - [x] `IgnorePatternWhitespace`
   - [x] `Singleline`
 - [x] Miscellaneous Constructs #1375

**Comment by anatsegev** [comment]
Joining the request to support the Singleline regex option.

**Comment by geoffreymcgill** [comment]
Hello @anatsegev - We're going to try and add support for `Singleline` Regex Option this week. If we can get it to work, the functionality will be included in the 1.14 release.

**Comment by LeonidVeriga** [comment]
@anatsegev,

In `1.14` release, we are including the following regex support enhancements:
- #1332 - Support Singleline Regex option
- #1360 - Support Multiline Regex option
- #1361 - Support IgnorePatternWhitespace Regex option
- #1363 - Support comments in Regex patterns
- #1362 - Support Inline Regex options (msx)
- #1364 - Support Regex Anchors
- #1365 - Support of Regex Backreferences

The changes are available in the `master` branch (Pull Request #1367)

**Comment by AndreyChechel** [comment]
The most of the enhancements were implemented. For the rest items separate issues have been created.
