### ISSUE TITLE
[v16] Remove obsolete items

### ISSUE THREAD

**Issue by LeonidVeriga** [bridgedotnet/Bridge#1750]
* [ ] In v15.0, the methods `Object.GetClassName` and  `Type.GetClassName` were marked as  `[Obsolete]`. (see #1749)
* [ ] In v15.0, constructor `[ObjectLiteral(DefaultValueMode.DefaultValue)]` and `enum DefaultValueMode`  were marked as `[Obsolete]` (see #1756)
* [ ] In v15.4, classes `Any<>` were marked as  `[Obsolete]` (see #1977)
