### ISSUE TITLE
New [Field] attribute to replace [FieldProperty]

### ISSUE THREAD

**Issue by LeonidVeriga** [bridgedotnet/Bridge#2234]
**EDIT1** Decided to remove - see #2478
**EDIT2** Decided to restore again - see #2742

Create a new `[Field]` attribute that functions exactly the same as [[FieldProperty]](http://bridge.net/docs/attribute-reference/#FieldProperty).

The `[FieldProperty]` attribute will be deprecated in Bridge **16.0** (see #2265) and deleted in **17.0** ( see #2236).

**Example**

```cs
public class Person
{
    // Old
    [FieldProperty]
    public string Name { get; set; }

    // New
    [Field]
    public string Name { get; set; }
}
```

**TODO**

- [x] Implement `[Field]` attribute in 15.8.0
- [x] Update [FieldProperty](http://bridge.net/docs/attribute-reference/#FieldProperty) and added [Field](http://bridge.net/docs/attribute-reference/#Field) documentation
- [x]  Create an issue to mark **FieldPropertyAttribute** class as  `[Obsolete]` in 16.0 (see #2265)
- [x] Create an issue in version 17.0 milestone to remove `[FieldProperty]` (see #2236)
- [x] Enable setting of attribute at Assembly and Class level

**Comment by geoffreymcgill** [comment]
The `[Field]` and `[FieldProperty]` attributes are no longer required because [as of](#1229) Bridge 16.0, all properties are defined in the JavaScript output as true JavaScript properties with real setters/getters.

The **FieldAttribute** will be removed immediately. The **FieldPropertyAttribute** class will be marked as `[Obsolete]` in Bridge 16.0 and will throw an Exception during compilation if used. See #2265.

If a simple field is required in JavaScript, please define as a Field in C#.

## See Also

- #1229
- #2478

**Comment by stopiccot** [comment]
So instead of replacing `[FieldProperty]`  with `[Field]` we should just remove `[FieldProperty]` and thats it?

**Comment by vladsch** [comment]
Yes, now Bridge uses `Object.defineProperty` for properties. So, it looks as fields. We are still reviewing to use Field attribute (it can be required where performance is important because access to a property is slower than access to a field)

**Comment by geoffreymcgill** [comment]
We are bringing back the [Field] attribute.

**Comment by vladsch** [comment]
Related to https://github.com/bridgedotnet/Bridge/issues/2742

**Comment by adamscura-rs** [comment]
This should be labeled "breaking-change" because the Obsolete attribute was applied with error: true. This causes the build to fail in existing projects.
