### ISSUE TITLE
Remove obsolete items

### ISSUE THREAD

**Issue by geoffreymcgill** [bridgedotnet/Bridge#2236]
- [x] Remove `[FieldProperty]` (see #2478)
- [x] Remove `List<T>.GetRange()` method, use `List<T>.GetRange(int, int)` instead (see #2255)
- [x] Remove `[Name(true)]` (see #2575)

**Comment by geoffreymcgill** [comment]
Done. Changes will be available in the Bridge 17.0 release.
