### ISSUE TITLE
Remove [Field] Attribute

### ISSUE THREAD

**Issue by geoffreymcgill** [bridgedotnet/Bridge#2478]
The `[Field]` Attribute was initially introduced in Bridge 16.0 as a replacement for the now obsolete `[FieldProperty]`, but since the JavaScript properties are now defined using **Object.defineProperty** instead of `set*/get*` methods, the **FieldAttribute** class is no longer required. 

## TODO

- [x] Remove **Field** from [documentation](https://github.com/bridgedotnet/Bridge/wiki/attribute-reference#field)
- [x] Update **FieldProperty** [documentation](https://github.com/bridgedotnet/Bridge/wiki/attribute-reference#fieldproperty) to state that the attribute is no longer required as of Bridge 16.0
- [x] Throw compiler Exception if `[FieldProperty]` is used, see #2265

## See Also

* #1229 Use Object initializer and/or Object.defineProperty() for class properties
* #2234 New [Field] attribute to replace [FieldProperty]

**Comment by kcudnik** [comment]
How i can achieve this functionality [deck](https://deck.net/d1cfc8bbae27189d6777d83cc23547e4) without Field property attribute ?

Interfaces in c# cant contain fields, so im forced to use properties, but since interface is external i need to mark them as property, and same i want in classes implementing interfaces, this was working fine until Field was removed.

**Comment by geoffreymcgill** [comment]
Hi @kcudnik – What is emitted in Main should be identical from 15.7 to 16.0. I think there was a fix to the `alias` values, but that shouldn't affect the implementation.

**Comment by kcudnik** [comment]
Im currently operating on 15.1 and just rebased to master, and i found this issue
Also im writing a forum post with problems that im founding after latest rabase, hope for some help

**Comment by geoffreymcgill** [comment]
@kcudnik – Please keep in mind that **master** is undergoing major changes right now, and personally I would not consider **master** stable right now.

Several additional significant changes are inbound during the next few weeks. That said, we're certainly interested in any issues you discover during your upgrade.

**Comment by kcudnik** [comment]
Thanks, im still working on that post, will send shortly'ish

**Comment by michaelcheers** [comment]
@geoffreymcgill, it could be useful because sometimes field properties are annoying when debugging in the javascript console.

**Comment by geoffreymcgill** [comment]
We are bringing back the `[Field]` attribute. Our goal is to implement right away and include in the upcoming **-beta2** release.

**Comment by michaelcheers** [comment]
![image](https://cloud.githubusercontent.com/assets/10186738/26568944/8917b2b8-4507-11e7-8e8a-881dbceb0993.png)
You can't get the value of x without using watch or the console whereas _x you can just see.

**Comment by geoffreymcgill** [comment]
Hi @michaelcheers – Can you provide some more comments on your comment above? I'm not sure I understand your comment.

**Comment by kcudnik** [comment]
I'm guessing he ment that if you are debugging your script, in js console when you expand object you can "see" field value, but wen using properties you need to call getXXX() to get and see actual value of field (which is property), and you can't see it directly when looking into debug window. I also find this annoying for properties.

**Comment by geoffreymcgill** [comment]
@kcudnik – I'm still not entirely sure what you mean. As of 16.0, there are no `get*()` methods. All C# properties are rendered as proper JavaScript properties.

If we use the following very simple Deck as an example;

https://deck.net/7988613b29a80fdd26925042806fe508

```csharp
public class Program
{
    public static void Main()
    {
        var p = new Person
        {
            Name = "Frank"
        };
        
        Console.WriteLine(p);
    }
}

public class Person
{
    public string Name { get; set; }
}
```

Then view the browsers **console** output, you should see the following:

<img width="198" alt="screenshot 2017-05-30 22 14 33" src="https://cloud.githubusercontent.com/assets/62210/26615751/87f48de6-4586-11e7-9d34-5d1f558cc942.png">

The `Name` property is available as a real property in console output. 

Hope this helps.

**Comment by kcudnik** [comment]
You are right, i was mistaken

**Comment by geoffreymcgill** [comment]
As well, with the upcoming **16.0.0-beta2** release (next week) you'll be able to set breakpoints in the C# .cs source file via the browser's developer tools **Sources** panel (in Chrome) or **Debugger** panel (in Firefox).

Source Map support has already been pushed to https://dev.deck.net:

https://dev.deck.net/7988613b29a80fdd26925042806fe508

<img width="806" alt="screenshot 2017-05-30 22 38 26" src="https://cloud.githubusercontent.com/assets/62210/26616247/6976f8c8-458a-11e7-8478-efa81138dbd7.png">

Hope this helps.

**Comment by kcudnik** [comment]
This is great! thanks!

**Comment by geoffreymcgill** [comment]
Video demonstrating Source Map:

![51cb28e0-3fde-11e7-8db6-9490a192ef23](https://cloud.githubusercontent.com/assets/62210/26620592/accfb4dc-45a0-11e7-8356-a7651eaf34ed.gif)

**Comment by kcudnik** [comment]
Very nice, it took a lot of work to make that work, great job!
