### ISSUE TITLE
Wrong return type for System.Collections.IList.Add

### ISSUE THREAD

**Issue by geoffreymcgill** [bridgedotnet/Bridge#2925]
The return type for **System.Collections.IList.Add** should be an `int`.

https://msdn.microsoft.com/en-us/library/system.collections.ilist.add(v=vs.110).aspx

```
Return Value
Type: System.Int32
The position into which the new element was inserted, or -1 to indicate that the item was not inserted into the collection.
```

## TODO

* [ ] Return type of `int` for **Add** method
* [ ] Update `[Template]` to ensure return value
* [ ] Change all instances of `item` arguments in **IList** to `value`

### Steps To Reproduce

https://deck.net/d0ac4650dd9bc90c4c459314f80a6637

```c#
using System;
using System.Collections;

public class Program
{
    public static void Main()
    {
        var msg = "Hello, World!";
        
        Console.WriteLine(msg);
    }
}
 public class Test : IList
    {
        public object this[int index] { get { throw new NotImplementedException(); } set { throw new NotImplementedException(); } }

        public bool IsReadOnly { get { throw new NotImplementedException(); } }

        public bool IsFixedSize { get { throw new NotImplementedException(); } }

        public int Count { get { throw new NotImplementedException(); } }

        public object SyncRoot { get { throw new NotImplementedException(); } }

        public bool IsSynchronized { get { throw new NotImplementedException(); } }

        public int Add(object value)
        {
            throw new NotImplementedException();
        }

        public void Clear()
        {
            throw new NotImplementedException();
        }

        public bool Contains(object value)
        {
            throw new NotImplementedException();
        }

        public void CopyTo(Array array, int index)
        {
            throw new NotImplementedException();
        }

        public IEnumerator GetEnumerator()
        {
            throw new NotImplementedException();
        }

        public int IndexOf(object value)
        {
            throw new NotImplementedException();
        }

        public void Insert(int index, object value)
        {
            throw new NotImplementedException();
        }

        public void Remove(object value)
        {
            throw new NotImplementedException();
        }

        public void RemoveAt(int index)
        {
            throw new NotImplementedException();
        }
    }
```

### Expected Result

**IList** should have an `int` return type, not `void`. 

https://github.com/bridgedotnet/Bridge/blob/master/Bridge/System/Collections/IList.cs#L12

```js
int Add(object value);
```

### Actual Result

```js
void Add(object item);
```
