### ISSUE TITLE
Support C# 7.1 and 7.2

### ISSUE THREAD

**Issue by geoffreymcgill** [bridgedotnet/Bridge#3491]
## TODO

- [x] readonly structs (C# 7.2)
- [x] default literals (C# 7.1)
- [x] async Main method (C# 7.1)
- [x] inferred Tuple Element Names (C# 7.1)
- [x] private protected access modifier (C# 7.2)
- [x] leading underscores in numeric literals (C# 7.2) ([deck](https://dev.deck.net/f53c5f9c58e5be53ba60e17fce00ec95))
- [x] non-trailing named arguments (C# 7.2)
- [x] ref struct (C# 7.2)
- [x] ref locals and returns

## See Also

* #2455
